### ISSUE TITLE
program info section (picture)

### ISSUE THREAD

**Issue by Darin-Hamouda** [lab-antwerp-1/group1-HackYourFuture#19]
- As a user I can see a nice picture beside the info about the programme.
  - this will be on the home page.
  - [ ] _there is a nice picture of a student (to the right of the text)_
  - this will be developed on the branch `4-home-pic`.

## HTML:
- [ ] use `img` to add the images.

## CSS:
- [ ] use `` as `height` and `width` for image size.
- [ ] use `0.5rem` as radius.

**Comment by denrique-alvarez** [comment]
At the end there was no image. Just titles and texts. It needs to be updated in the development strategy.
