### ISSUE TITLE
Planning documents progress

### ISSUE THREAD

**Issue by Darin-Hamouda** [lab-antwerp-1/group1-HackYourFuture#9]
# Planning documents:
- [x] Constraints.
- [x] Communication plan.
- [x] User personas.
- [x] Backlog.
- [x] Development strategy (First draft)
- [x] Development strategy (Final)
- [x] Design wireframes.

**Comment by samirm00** [comment]
Very good job , some ideas maybe they will be helpful:
1- you have different users  students, coaches , volunteer ... ,
each user may have a different stories , for example , if the user is a `student` he or she will probably be interested in the curriculum , date of registration , deadline , if the user is a `coach`  he will have a different story ,  and also student and coach both could have shared stories like how to contact HYF.

2- for your label `Must Have `, I don't think it is necessary. it  doesn't make a lot of different now , but in the future when you build a bigger projects , you will have a lot of labels , and one extra label will be an extra think to care about   , only use the necessary labels

**Comment by mauricemat** [comment]
> Very good job , some ideas maybe they will be helpful: 1- you have different users students, coaches , volunteer ... , each user may have a different stories , for example , if the user is a `student` he or she will probably be interested in the curriculum , date of registration , deadline , if the user is a `coach` he will have a different story , and also student and coach both could have shared stories like how to contact HYF.
> 
> 2- for your label `Must Have `, I don't think it is necessary. it doesn't make a lot of different now , but in the future when you build a bigger projects , you will have a lot of labels , and one extra label will be an extra think to care about , only use the necessary labels
> 
> 3- you don't have to create a sperate wireframe for each page , you can put all pages together in one signal wireframe file

Hello Samir,
Thank you a lot for your advice.
Regarding the first point you mentioned in your comment, we created different _User Personas_ and the issues are based on the interests of those different User Personas. 
Thanks
